default: &default
  adapter: mysql2
  encoding: utf8
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: ergonaut_dev
  pool: 5
  username: ergonaut_dev
  password: blitzkrieg

test:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: ergonaut_test
  pool: 5
  username: ergonaut_dev
  password: blitzkrieg

production:
  <<: *default
  url: <%= ENV['DATABASE_URL'] %>

production:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  url: <%= ENV['DATABASE_URL'] %>
